builds:
- env:
  - CGO_ENABLED=0
archive:
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  replacements:
    darwin: macOS
    386: 32-bit
    amd64: 64-bit
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brew:
  github:
    owner: gabrielrobert
    name: homebrew-tap
  folder: Formula
  install: |
    bin.install "xavtool"

scoop:
  bucket:
    owner: gabrielrobert
    name: scoop-bucket
  homepage:  https://github.com/gabrielrobert/xavtool
  description: Xamarin Automating Version Tool
  license: MIT