language: go

os:
  - linux

go:
  - 1.x

script:
  - go test -v

# after_success:
#   - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL http://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux