version: "{build}"

image: Visual Studio 2017

clone_folder: c:\gopath\src\github.com\gabrielrobert\xavtool

environment:
  GOPATH: C:\gopath
  GOVERSION: 1.10.x

install:
  - set PATH=%GOPATH%\bin;C:\go\bin;%PATH%
  - go version
  - go env
  - go get github.com/gabrielrobert/xavtool

build_script:
  - go build

test_script:
  - go test -v