version: "{build}"

image: Visual Studio 2017

clone_folder: c:\gopath\src\github.com\gabrielrobert\xavtool

environment:
  GOPATH: C:\gopath
  GOVERSION: 1.10.x

install:
  - set PATH=%GOPATH%\bin;C:\go\bin;%PATH%
  - go version
  - go env
  - go get github.com/gabrielrobert/xavtool
  - ps: iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
  - ps: scoop bucket add goreleaser https://github.com/goreleaser/scoop-bucket.git
  - ps: scoop install goreleaser
  - goreleaser -v
  - go get -t -v ./...

build_script:
  - go build

test_script:
  - go test -v

after_test:
  - goreleaser --rm-dist --snapshot
  - choco pack

artifacts:
  - path: '**\*.nupkg'

deploy:
  provider: Environment
  name: Chocolatey
  artifact: /.*\.nupkg/
  on:
    branch: master